/* Manifiesto de problemas. `ready:true` = módulo js/problems/NUM.js existente.
   La portada (index.html) lo usa para armar las tarjetas.               */
window.MANIFEST = {
  blocks: [
    { id: "grafos", title: { es: "Bloque 1 · Grafos", en: "Block 1 · Graphs" } },
    { id: "arboles", title: { es: "Bloque 2 · Árboles", en: "Block 2 · Trees" } },
    { id: "intervalos", title: { es: "Bloque 3 · Intervalos", en: "Block 3 · Intervals" } },
    { id: "heaps-topk", title: { es: "Bloque 4 · Heaps y Top-K", en: "Block 4 · Heaps & Top-K" } },
    { id: "sliding-window-stack", title: { es: "Bloque 6 · Sliding Window y Pilas", en: "Block 6 · Sliding Window & Stacks" } },
    { id: "dp", title: { es: "Bloque 7 · Programación Dinámica", en: "Block 7 · Dynamic Programming" } },
  ],
  problems: [
    // ---- Grafos ----
    { num: 200, title: "Number of Islands", dif: "M", block: "grafos", tags: ["DFS", "grid"], ready: true },
    { num: 994, title: "Rotting Oranges", dif: "M", block: "grafos", tags: ["BFS", "grid"], ready: true },
    { num: 695, title: "Max Area of Island", dif: "M", block: "grafos", tags: ["DFS", "grid"], ready: true },
    { num: 542, title: "01 Matrix", dif: "M", block: "grafos", tags: ["BFS", "grid"], ready: true },
    { num: 1091, title: "Shortest Path in Binary Matrix", dif: "M", block: "grafos", tags: ["BFS", "grid"], ready: true },
    { num: 417, title: "Pacific Atlantic Water Flow", dif: "M", block: "grafos", tags: ["DFS", "grid"], ready: true },
    { num: 79, title: "Word Search", dif: "M", block: "grafos", tags: ["backtracking", "grid"], ready: true },
    { num: 207, title: "Course Schedule", dif: "M", block: "grafos", tags: ["topológico", "BFS"], ready: true },
    { num: 210, title: "Course Schedule II", dif: "M", block: "grafos", tags: ["topológico", "BFS"], ready: true },
    { num: 269, title: "Alien Dictionary", dif: "H", block: "grafos", tags: ["topológico"], ready: true },
    { num: 127, title: "Word Ladder", dif: "H", block: "grafos", tags: ["BFS"], ready: true },
    { num: 126, title: "Word Ladder II", dif: "H", block: "grafos", tags: ["BFS", "backtracking"], ready: true },
    { num: 261, title: "Graph Valid Tree", dif: "M", block: "grafos", tags: ["union-find"], ready: true },
    { num: 323, title: "Connected Components", dif: "M", block: "grafos", tags: ["union-find"], ready: true },
    { num: 128, title: "Longest Consecutive Sequence", dif: "M", block: "grafos", tags: ["conjunto"], ready: true },
    { num: 547, title: "Number of Provinces", dif: "M", block: "grafos", tags: ["union-find", "DFS"], ready: true },
    { num: 743, title: "Network Delay Time", dif: "M", block: "grafos", tags: ["Dijkstra"], ready: true },
    { num: 787, title: "Cheapest Flights K Stops", dif: "M", block: "grafos", tags: ["Bellman-Ford"], ready: true },
    { num: 133, title: "Clone Graph", dif: "M", block: "grafos", tags: ["BFS", "DFS"], ready: true },
    { num: 1192, title: "Critical Connections", dif: "H", block: "grafos", tags: ["Tarjan"], ready: true },
    // ---- Árboles ----
    { num: 236, title: "Lowest Common Ancestor", dif: "M", block: "arboles", tags: ["DFS", "recursión"], ready: true },
    { num: 1644, title: "LCA II (puede faltar nodo)", dif: "M", block: "arboles", tags: ["DFS"], ready: true },
    { num: 103, title: "Zigzag Level Order", dif: "M", block: "arboles", tags: ["BFS", "niveles"], ready: true },
    { num: 199, title: "Right Side View", dif: "M", block: "arboles", tags: ["BFS", "niveles"], ready: true },
    { num: 987, title: "Vertical Order Traversal", dif: "H", block: "arboles", tags: ["BFS", "coordenadas"], ready: true },
    { num: 124, title: "Max Path Sum", dif: "H", block: "arboles", tags: ["DFS", "recursión"], ready: true },
    { num: 543, title: "Diameter of Binary Tree", dif: "M", block: "arboles", tags: ["DFS"], ready: true },
    { num: 863, title: "All Nodes Distance K", dif: "M", block: "arboles", tags: ["BFS", "grafo"], ready: true },
    { num: 98, title: "Validate BST", dif: "M", block: "arboles", tags: ["DFS", "inorden"], ready: true },
    { num: 105, title: "Build Tree (Pre+In)", dif: "M", block: "arboles", tags: ["recursión"], ready: true },
    { num: 337, title: "House Robber III", dif: "M", block: "arboles", tags: ["DP en árbol"], ready: true },
    { num: 297, title: "Serialize & Deserialize", dif: "H", block: "arboles", tags: ["BFS", "DFS"], ready: true },
    // ---- Intervalos ----
    { num: 56, title: "Merge Intervals", dif: "M", block: "intervalos", tags: ["sort", "intervalos"], ready: true },
    { num: 253, title: "Meeting Rooms II", dif: "M", block: "intervalos", tags: ["sweep line", "min-heap"], ready: true },
    { num: 2402, title: "Meeting Rooms III", dif: "H", block: "intervalos", tags: ["min-heap"], ready: true },
    { num: 1094, title: "Car Pooling", dif: "M", block: "intervalos", tags: ["sweep line"], ready: true },
    // ---- Heaps y Top-K ----
    { num: 215, title: "Kth Largest Element", dif: "M", block: "heaps-topk", tags: ["min-heap"], ready: true },
    { num: 347, title: "Top K Frequent Elements", dif: "M", block: "heaps-topk", tags: ["bucket sort", "heap"], ready: true },
    { num: 973, title: "K Closest Points to Origin", dif: "M", block: "heaps-topk", tags: ["max-heap"], ready: true },
    { num: 295, title: "Find Median from Data Stream", dif: "H", block: "heaps-topk", tags: ["min-heap", "max-heap"], ready: true },
    { num: 23, title: "Merge k Sorted Lists", dif: "H", block: "heaps-topk", tags: ["min-heap", "lista enlazada"], ready: true },
    { num: 621, title: "Task Scheduler", dif: "M", block: "heaps-topk", tags: ["max-heap", "cola"], ready: true },
    // ---- Sliding Window y Pilas ----
    { num: 3, title: "Longest Substring Without Repeating", dif: "M", block: "sliding-window-stack", tags: ["sliding window"], ready: true },
    { num: 76, title: "Minimum Window Substring", dif: "H", block: "sliding-window-stack", tags: ["sliding window"], ready: true },
    { num: 42, title: "Trapping Rain Water", dif: "H", block: "sliding-window-stack", tags: ["two pointers"], ready: true },
    { num: 84, title: "Largest Rectangle in Histogram", dif: "H", block: "sliding-window-stack", tags: ["pila monótona"], ready: true },
    { num: 394, title: "Decode String", dif: "M", block: "sliding-window-stack", tags: ["pila"], ready: true },
    // ---- Programación Dinámica ----
    { num: 322, title: "Coin Change", dif: "M", block: "dp", tags: ["DP"], ready: true },
    { num: 139, title: "Word Break", dif: "M", block: "dp", tags: ["DP"], ready: true },
    { num: 55, title: "Jump Game", dif: "M", block: "dp", tags: ["greedy"], ready: true },
    { num: 5, title: "Longest Palindromic Substring", dif: "M", block: "dp", tags: ["two pointers"], ready: true },
  ],
};
